import React,{useState,useRef} from 'react';
import {Upload,FileText,Link,ArrowRight,BookOpen} from 'lucide-react';
import {Modal,Field} from './Modal';
import {importFile,importWebsite} from '../lib/imports';
import {STYLES,MAX_SOURCE_CHARS,newBook,uid,splitSource} from '../../shared/book.mjs';
export default function NewBook({onClose,onCreate,onAdapt,onImport,notify,initial}){
  const [tab,setTab]=useState('file'),[text,setText]=useState(initial?.source.text||''),[name,setName]=useState(initial?.source.name||''),[url,setUrl]=useState(''),[loading,setLoading]=useState('');const fileRef=useRef();
  const [options,setOptions]=useState(initial?.options||{spreads:4,audience:'All ages',language:'English',style:'Watercolor',mode:'Keep the original story'});
  const setOption=(k,v)=>setOptions(o=>({...o,[k]:v}));
  async function read(file){if(!file)return;setLoading('Reading your document…');try{const data=await importFile(file,setLoading);if(data.book){onImport(data.book);return;}setText(data.text);setName(data.name);}catch(e){notify(e.message,'error');}finally{setLoading('');}}
  async function getWebsite(){setLoading('Reading the web page…');try{const data=await importWebsite(url);setText(data.text);setName(data.name);}catch(e){notify(e.message,'error');}finally{setLoading('');}}
  function manual(){if(text.length>12000){notify('For a manual layout, use a short story under 12,000 characters. Adapt this source to condense a longer book.','error');return;}const book=newBook(name||'My picture book');Object.assign(book,{style:options.style,audience:options.audience,language:options.language,source:{name:name||'Pasted story',text}});const paragraphs=text.trim()?splitSource(text,Math.max(100,Math.ceil(text.length/Number(options.spreads)))):[];book.pages=Array.from({length:Math.max(Number(options.spreads),paragraphs.length)},(_,i)=>({id:uid(),title:i===0?book.title:`Chapter ${i+1}`,text:paragraphs[i]||'',scene:'',sourceNote:'Original text, arranged manually.',image:'',alt:''}));onCreate(book);}
  return <Modal title="A story worth picturing" wide onClose={onClose}><p className="intro">Bring a story. Make it your own, one spread at a time.</p><div className="tabs source-tabs" role="tablist" aria-label="Source type">{[['file',Upload,'Upload a book'],['text',FileText,'Paste text'],['url',Link,'Website']].map(([id,Icon,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>
    {tab==='file'&&<div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();read(e.dataTransfer.files[0]);}}><BookOpen size={35}/><strong>Drop your story here</strong><span>PDF, DOCX, TXT, Markdown, or a saved project · up to 25 MB</span><button className="secondary" onClick={()=>fileRef.current.click()} disabled={!!loading}>Choose a file</button><input ref={fileRef} type="file" hidden accept=".pdf,.docx,.txt,.md,.html,.htm,.json" onChange={e=>read(e.target.files[0])}/></div>}
    {tab==='url'&&<div className="url-entry"><Field label="Public web page"><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/my-story"/></Field><button className="secondary" disabled={!url||!!loading} onClick={getWebsite}>Import page</button><small>Public text pages only. Pages behind logins or paywalls cannot be imported.</small></div>}
    {loading&&<p className="status-line" role="status">{loading}</p>}
    {(text||tab==='text')&&<><Field label="Book title"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Give your story a name" maxLength={200}/></Field><Field label="Source text"><textarea className="source-text" value={text} onChange={e=>setText(e.target.value)} maxLength={MAX_SOURCE_CHARS} placeholder="Paste your story, a chapter, or a whole novel…"/></Field><p className="source-count">{text.trim()?text.trim().split(/\s+/).length.toLocaleString():0} words · {text.length.toLocaleString()} / {MAX_SOURCE_CHARS.toLocaleString()} characters</p></>}
    <div className="options-grid"><Field label="Book length"><select value={options.spreads} onChange={e=>setOption('spreads',Number(e.target.value))}>{[4,6,8,12,16,24].map(n=><option key={n} value={n}>{n*2} pages · {n} spreads</option>)}</select></Field><Field label="Readers"><select value={options.audience} onChange={e=>setOption('audience',e.target.value)}>{['All ages','Ages 3–5','Ages 6–8','Ages 9–12','Teen & adult'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Art style"><select value={options.style} onChange={e=>setOption('style',e.target.value)}>{STYLES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Language"><input value={options.language} maxLength={50} onChange={e=>setOption('language',e.target.value)}/></Field></div><Field label="Adaptation"><select value={options.mode} onChange={e=>setOption('mode',e.target.value)}><option>Keep the original story</option><option>Retell simply for the selected readers</option><option>Keep a lyrical, read-aloud rhythm</option></select></Field>
    <small className="rights-note">Use stories you own, have permission to adapt, or that are in the public domain. Text goes to your selected generation service only when you choose Adapt story.</small><div className="modal-actions"><button className="secondary" disabled={!!loading} onClick={manual}>Start manually</button><button className="primary" disabled={text.trim().length<40||!!loading} onClick={()=>onAdapt({name:name||'My story',text},options)}>Adapt story <ArrowRight size={17}/></button></div></Modal>;
}
