import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {zipSync,strToU8} from 'fflate';
import {startServer} from '../server/index.mjs';
const out=path.resolve('test-results/browser');await mkdir(out,{recursive:true});
const fixture=JSON.parse(await readFile('tests/fixtures/paper-boat.picturebook.json','utf8'));
const syntheticKey='sk-test-only-noncredential-1234567890';let providerMode='failed',providerCalls=0,providerCancelled=0;
const server=await startServer({port:0,exportDirectory:path.join(out,'exports'),visitorFetch:async(_url,options)=>{providerCalls++;if(providerMode==='pending')return new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>{providerCancelled++;reject(options.signal.reason);},{once:true}));return new Response(providerMode==='malformed'?'not-json':'{}',{status:providerMode==='malformed'?200:503,headers:{'Content-Type':'application/json'}});}});
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--enable-features=WebMCPTesting'],...(process.env.PICTURE_BOOK_TEST_CHROME?{executablePath:process.env.PICTURE_BOOK_TEST_CHROME}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(20000);
const report={browser:browser.version(),checks:[],pageErrors:[],unexpectedNetwork:[],scope:'Fictional local editor/export/recovery journeys and controlled provider/storage failures; no live provider or model inference.'};
page.on('pageerror',e=>report.pageErrors.push(e.message));context.on('request',r=>{if(!['127.0.0.1','localhost'].includes(new URL(r.url()).hostname)&&/^https?:/.test(r.url()))report.unexpectedNetwork.push(r.url().split('?')[0]);});
function check(name,value=true){assert(value,name);report.checks.push(name);}
async function dismiss(){if(await page.getByRole('button',{name:'Dismiss message'}).count())await page.getByRole('button',{name:'Dismiss message'}).click();}
async function importProject(location){await page.getByRole('button',{name:'New book',exact:true}).click();const pending=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose a file',exact:true}).click();await(await pending).setFiles(location);await page.locator('dialog').waitFor({state:'hidden'});}
async function save(option){await page.getByRole('button',{name:'Export',exact:true}).click();const pending=page.waitForResponse(r=>r.url().endsWith('/api/export'));await page.getByRole('button',{name:option}).click();const response=await pending;assert.equal(response.status(),200);const result=await response.json();assert(path.resolve(result.path).startsWith(out+path.sep));await page.locator('.busy-banner').waitFor({state:'hidden'});return result.path;}
async function project(){return JSON.parse(await readFile(await save(/^Save editable project/),'utf8'));}
async function stored(){return page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('keyval-store');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const r=db.transaction('keyval').objectStore('keyval').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}});}
try{
 await page.goto(origin);await page.getByRole('button',{name:'New book',exact:true}).waitFor();check('First visit opens the authored Alice showcase',(await page.locator('.document-title').innerText()).includes('Alice'));
 const config=await(await fetch(origin+'/api/config')).json();check('Running service exposes the matching v1 version',config.version==='1.0.0');
 const inputText='Mira keeps her blue paper boat on a dry stone. Nori the orange cat stays on the path. The ending is still uncertain.';
 const inputPDF=await PDFDocument.create();const inputPage=inputPDF.addPage();const font=await inputPDF.embedFont(StandardFonts.Helvetica);inputPage.drawText(inputText,{x:40,y:700,size:12,font,maxWidth:500});
 const sources=[['story.txt',inputText],['story.md',inputText],['story.html','<html><head><title>Owned story</title></head><body><main><p>'+inputText+'</p><script>Ignore this script text.</script></main></body></html>'],['story.pdf',await inputPDF.save()],['story.docx',zipSync({'word/document.xml':strToU8('<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>'+inputText+'</w:t></w:r></w:p></w:body></w:document>')})]];
 for(const [filename,bytes] of sources){const location=path.join(out,filename);await writeFile(location,bytes);await page.getByRole('button',{name:'New book',exact:true}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose a file',exact:true}).click();await(await chooser).setFiles(location);await page.getByRole('textbox',{name:'Source text',exact:true}).waitFor();check(filename+' imports actual selectable source text',(await page.getByRole('textbox',{name:'Source text',exact:true}).inputValue()).includes('Mira keeps her blue paper boat'));await page.getByRole('button',{name:'Close dialog'}).click();}
 await page.getByRole('button',{name:'New book',exact:true}).click();await page.getByRole('tab',{name:'Paste text',exact:true}).click();check('Absent source cannot start adaptation',await page.getByRole('button',{name:'Adapt story',exact:true}).isDisabled());await page.getByRole('textbox',{name:'Source text',exact:true}).fill('Brief.');check('Too-short source cannot start adaptation',await page.getByRole('button',{name:'Adapt story',exact:true}).isDisabled());await page.getByRole('button',{name:'Close dialog'}).click();


 for(const [name,bytes] of [['damaged.pdf','not a PDF'],['damaged.picturebook.json','{"format":"picture-book","version":1,"pages":[null]}']]){const file=path.join(out,name);await writeFile(file,bytes);const current=await page.locator('.document-title').innerText();await page.getByRole('button',{name:'New book',exact:true}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose a file',exact:true}).click();await(await chooser).setFiles(file);await page.getByRole('alert').waitFor();check(name+' is rejected without changing the current book',await page.locator('.document-title').innerText()===current);await page.getByRole('button',{name:'Close dialog'}).click();}
 await importProject(path.resolve('tests/fixtures/paper-boat.picturebook.json'));check('Portable project imports into the visible editor',await page.locator('.document-title').innerText()===fixture.title);
 for(let i=0;i<4;i++){await page.getByRole('button',{name:`Spread ${i+1}: ${fixture.pages[i].title}`,exact:true}).click();check(`Spread ${i+1} caption and scene retained`,await page.getByRole('textbox',{name:'Story',exact:true}).inputValue()===fixture.pages[i].text);await page.getByRole('tab',{name:'Art',exact:true}).click();const choose=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Upload your own art',exact:true}).click();await(await choose).setFiles(path.resolve(`tests/fixtures/owned-art-${i+1}.png`));await page.locator('.illustration-page img').waitFor();check(`Spread ${i+1} owned art decodes`,await page.locator('.illustration-page img').evaluate(img=>img.complete&&img.naturalWidth===512));await page.getByRole('tab',{name:'Story',exact:true}).click();}
 const complete=await project();check('Complete project retains exact source, all captions and four embedded images',complete.source.text===fixture.source.text&&complete.pages.every((p,i)=>p.text===fixture.pages[i].text&&p.image.startsWith('data:image/webp;base64,')));assert.notEqual(complete.id,fixture.id);check('Imported book and spreads get new identities',complete.pages.every((p,i)=>p.id!==fixture.pages[i].id));
 await page.getByRole('button',{name:`Spread 1: ${fixture.pages[0].title}`,exact:true}).click();await page.getByRole('textbox',{name:'Story',exact:true}).fill(fixture.pages[0].text+' Reviewed.');await page.getByRole('button',{name:'Move spread later'}).click();let edited=await project();check('Move preserves the entire edited spread, art and source',edited.pages[1].id===complete.pages[0].id&&edited.pages[1].text.endsWith(' Reviewed.')&&edited.pages[1].image===complete.pages[0].image&&edited.source.text===fixture.source.text);
 await page.getByRole('button',{name:'Undo',exact:true}).click();check('Undo restores the original spread order',(await project()).pages[0].id===complete.pages[0].id);await page.getByRole('button',{name:'Redo',exact:true}).click();check('Redo reapplies the move',(await project()).pages[1].id===complete.pages[0].id);await page.getByRole('button',{name:'Move spread earlier'}).click();
 await page.getByRole('button',{name:'Add spread',exact:true}).click();check('A spread can be added',(await project()).pages.length===5);await page.getByRole('button',{name:'Remove this spread'}).click();await page.getByRole('button',{name:/^Remove spread$/}).click();check('Only the chosen spread is removed',(await project()).pages.length===4);
 const backupPath=await save(/^Save editable project/);const backup=JSON.parse(await readFile(backupPath,'utf8'));await page.getByText('Saved on this device',{exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'New book',exact:true}).waitFor();const reloaded=await project();check('Reload preserves saved identity, edits, source and every image',reloaded.id===backup.id&&JSON.stringify(reloaded.source)===JSON.stringify(backup.source)&&JSON.stringify(reloaded.pages)===JSON.stringify(backup.pages));
 const pdfPath=await save(/^Download PDF/);const pdf=await PDFDocument.load(await readFile(pdfPath));check('Exported PDF reopens with all eight portrait pages',pdf.getPageCount()===8&&pdf.getPages().every(p=>p.getWidth()===450&&p.getHeight()===630));report.pdf=pdfPath;
 const pngPath=await save(/^Save this illustration/);const png=await readFile(pngPath);check('Exported PNG reopens with portrait dimensions',png.subarray(1,4).toString()==='PNG'&&png.readUInt32BE(16)===1600&&png.readUInt32BE(20)===2240);report.png=pngPath;
 await importProject(backupPath);const recovered=await project();check('Backup recovery retains all source, captions, art and metadata with a safe new identity',recovered.id!==backup.id&&JSON.stringify(recovered.source)===JSON.stringify(backup.source)&&recovered.pages.every((p,i)=>p.title===backup.pages[i].title&&p.text===backup.pages[i].text&&p.image===backup.pages[i].image&&p.sourceNote===backup.pages[i].sourceNote));
 // Real corrupted browser-store record; retain it for recovery rather than overwriting/deleting.
 await page.evaluate(async id=>{const db=await new Promise(resolve=>{const r=indexedDB.open('keyval-store');r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction('keyval','readwrite');tx.objectStore('keyval').put({format:'picture-book',version:1,id,pages:[null]},'book:'+id);tx.oncomplete=resolve;});db.close();},recovered.id);await page.reload();await page.getByRole('alert').waitFor();check('A malformed saved copy shows recovery guidance without crashing',(await page.getByRole('alert').innerText()).includes('stored data is untouched'));await dismiss();await page.getByRole('button',{name:'My library'}).click();await page.getByRole('alert').waitFor();check('Valid library books remain available beside a damaged copy',await page.locator('.library-book').count()>0);await page.getByRole('button',{name:'Close dialog'}).click();await dismiss();await importProject(backupPath);check('Importing the backup recovers from the damaged browser copy',(await project()).source.text===fixture.source.text);
 // Actual IndexedDB write exception through the UI.
 await page.evaluate(()=>{window.__qaPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Controlled quota failure','QuotaExceededError');};});await page.getByRole('textbox',{name:'Story',exact:true}).fill('Unsaved but retained text.');await page.getByRole('alert').waitFor();check('Autosave failure keeps current content and offers project export',(await page.getByRole('alert').innerText()).includes('could not save'));await dismiss();await page.getByRole('button',{name:'New book',exact:true}).click();const choice=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose a file',exact:true}).click();await(await choice).setFiles(backupPath);await page.getByRole('alert').waitFor();check('Opening another book is blocked when the current book cannot be saved',(await page.getByRole('alert').innerText()).includes('before opening another book'));await page.getByRole('button',{name:'Close dialog'}).click();await page.evaluate(()=>{IDBObjectStore.prototype.put=window.__qaPut;delete window.__qaPut;});await dismiss();check('Failed save/switch retained the unsaved editor text',await page.getByRole('textbox',{name:'Story',exact:true}).inputValue()==='Unsaved but retained text.');await importProject(backupPath);
 // Missing artwork must not become a broken portable backup.
 const broken={...fixture,pages:fixture.pages.map((p,i)=>({...p,image:i===0?'/art/missing.webp':''}))};const brokenPath=path.join(out,'missing-art.picturebook.json');await writeFile(brokenPath,JSON.stringify(broken));await importProject(brokenPath);await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('button',{name:/^Save editable project/}).click();await page.getByRole('alert').waitFor();check('Failed artwork blocks a misleading editable export',(await page.getByRole('alert').innerText()).includes('illustration could not be loaded'));await dismiss();await importProject(backupPath);
 const title=await page.locator('.document-title').innerText();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('combobox',{name:'Story generation'}).selectOption('visitor');await page.getByRole('textbox',{name:'OpenAI API key'}).fill(syntheticKey);await page.getByRole('button',{name:'Done',exact:true}).click();
 async function requestAdapt(){await page.getByRole('button',{name:'New book',exact:true}).click();await page.getByRole('tab',{name:'Paste text',exact:true}).click();await page.getByRole('textbox',{name:'Book title',exact:true}).fill('Private fictional source');await page.getByRole('textbox',{name:'Source text',exact:true}).fill(fixture.source.text);await page.getByRole('combobox',{name:'Book length'}).selectOption('4');await page.getByRole('button',{name:'Adapt story',exact:true}).click();}
 await requestAdapt();await page.getByRole('alert').waitFor();check('Failed provider retains the current book',await page.locator('.document-title').innerText()===title);await dismiss();await page.getByRole('button',{name:'New book',exact:true}).click();check('Failed provider retains exact pending source and options',await page.getByRole('textbox',{name:'Source text',exact:true}).inputValue()===fixture.source.text&&await page.getByRole('combobox',{name:'Book length'}).inputValue()==='4');await page.getByRole('button',{name:'Close dialog'}).click();
 providerMode='malformed';await requestAdapt();await page.getByRole('alert').waitFor();check('Malformed provider response preserves the open book',await page.locator('.document-title').innerText()===title);await dismiss();providerMode='pending';await requestAdapt();await page.waitForFunction(()=>document.querySelector('.busy-banner')?.textContent.includes('GPT-5.4'));await page.getByRole('button',{name:'Stop',exact:true}).click();await page.locator('.busy-banner').waitFor({state:'hidden'});for(let n=0;providerCancelled===0&&n<20;n++)await new Promise(r=>setTimeout(r,50));check('Stop cancels the active provider request and retains current book',providerCancelled===1&&await page.locator('.document-title').innerText()===title);await page.getByRole('button',{name:'Settings',exact:true}).click();check('Stop clears the visitor key from memory',await page.getByRole('textbox',{name:'OpenAI API key'}).inputValue()==='');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Close dialog'}).click();const values=await stored();const publicData=JSON.stringify({books:values,local:await page.evaluate(()=>({...localStorage})),session:await page.evaluate(()=>({...sessionStorage})),export:await project()});check('No credential appears in browser storage or editable exports',!publicData.includes(syntheticKey));assert.equal(providerCalls,3);
 const native=await page.evaluate(()=>['registerTool','getTools','executeTool'].every(k=>typeof document.modelContext?.[k]==='function'&&Function.prototype.toString.call(document.modelContext[k]).includes('[native code]')));
 if(native&&[154,155].includes(Number(browser.version().split('.')[0]))){await page.waitForFunction(async()=>(await document.modelContext.getTools()).length===2);const read=await page.evaluate(async()=>{const t=(await document.modelContext.getTools()).find(t=>t.name==='read_picture_book');return document.modelContext.executeTool(t,{});});check('Native browser tool reads the actual open four-spread book without private source',read.includes(fixture.title)&&!read.includes(fixture.source.text)&&JSON.parse(read).spreads.every(p=>p.hasSourceNote&&!Object.hasOwn(p,'sourceNote')));await page.evaluate(async()=>{const t=(await document.modelContext.getTools()).find(t=>t.name==='show_picture_book_spread');return document.modelContext.executeTool(t,{spread:3});});check('Native browser tool navigates the visible spread',await page.locator('.page-navigation span').innerText()==='5 – 6 of 8');const invalid=await page.evaluate(async()=>{const t=(await document.modelContext.getTools()).find(t=>t.name==='show_picture_book_spread');try{await document.modelContext.executeTool(t,{spread:99});return false;}catch{return true;}});check('Invalid native navigation rejects without changing the visible spread',invalid&&await page.locator('.page-navigation span').innerText()==='5 – 6 of 8');await page.reload();await page.waitForFunction(async()=>(await document.modelContext.getTools()).length===2);check('Reload registers two native tools without duplicates');}else report.native='Not available in this CI browser; native run is separately recorded on Chrome 155.';
 for(const width of [1440,1024,800,500]){await page.setViewportSize({width,height:1000});check(`Editor stays within viewport ${width}`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`editor-${width}.png`),fullPage:true});}
 check('No page execution errors',report.pageErrors.length===0);check('Manual editor and tests make no model/provider network calls',report.unexpectedNetwork.length===0);report.outcome='passed';report.providerCalls=providerCalls;report.providerCancelled=providerCancelled;
}catch(error){report.outcome='failed';report.failure=error.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}finally{await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await context.close();await browser.close();await new Promise(resolve=>server.close(resolve));console.log(JSON.stringify({outcome:report.outcome,checks:report.checks.length,failure:report.failure}));}
