import {_electron as electron} from 'playwright';import {createRequire} from 'node:module';import {readFile,mkdir,writeFile,access} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
if(process.platform!=='win32'){console.log('Windows portable consumer is checked by the Windows job.');process.exit(0);}
const require=createRequire(import.meta.url),exe=process.env.PICTURE_BOOK_TEST_DESKTOP||require('electron'),appFolder=process.env.PICTURE_BOOK_TEST_APP||process.cwd(),out=path.resolve('test-results/desktop');await mkdir(out,{recursive:true});const profile=path.join(out,'profile-'+Date.now());await mkdir(profile,{recursive:true});const fixture=path.resolve('tests/fixtures/paper-boat.picturebook.json');const pkg=JSON.parse(await readFile(path.join(appFolder,'package.json'),'utf8'));const report={version:pkg.version,profile,checks:[],pageErrors:[],edition:process.env.PICTURE_BOOK_TEST_DESKTOP?'released portable consumer':'source desktop'};let app;
async function launch(){const args=[`--data-dir=${profile}`];if(!process.env.PICTURE_BOOK_TEST_DESKTOP)args.push(appFolder);app=await electron.launch({executablePath:exe,args,env:{...process.env,HOME:path.join(out,'home'),USERPROFILE:path.join(out,'home'),APPDATA:path.join(out,'home/AppData/Roaming'),LOCALAPPDATA:path.join(out,'home/AppData/Local')},timeout:60000});const actual=await app.evaluate(({app})=>({version:app.getVersion(),profile:app.getPath('userData')}));assert.equal(path.resolve(actual.profile),path.resolve(profile));assert.equal(actual.version,pkg.version);const page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.pageErrors.push(e.message));await page.getByRole('button',{name:'New book',exact:true}).waitFor();return page;}
function check(name,value=true){assert(value,name);report.checks.push(name);}
try{let page=await launch();check('Actual Electron process uses the owned disposable profile and matching app version');check('Renderer runs at stable local origin',page.url()==='http://127.0.0.1:4174/');const preferences=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());check('Renderer keeps context isolation, sandbox and Node disabled',preferences.contextIsolation&&preferences.sandbox&&!preferences.nodeIntegration);
await page.getByRole('button',{name:'New book',exact:true}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose a file',exact:true}).click();await(await chooser).setFiles(fixture);await page.locator('dialog').waitFor({state:'hidden'});const original=await page.getByRole('textbox',{name:'Story',exact:true}).inputValue();await page.getByRole('textbox',{name:'Story',exact:true}).fill(original+' Desktop revision.');await page.getByText('Saved on this device',{exact:true}).waitFor({state:'attached'});check('Imported fictional book can be edited and saved');await app.close();app=null;page=await launch();check('A real app restart preserves the saved revision',await page.getByRole('textbox',{name:'Story',exact:true}).inputValue()===original+' Desktop revision.');
await page.getByRole('button',{name:'Settings',exact:true}).click();check('Settings shows the matching release version',await page.getByText('Picture Book '+pkg.version,{exact:true}).count()===1);await page.getByRole('button',{name:'Done',exact:true}).click();
await page.getByRole('button',{name:'Export',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/export'));await page.getByRole('button',{name:/^Save editable project/}).click();const result=await(await response).json();check('Portable editor saves an actual project to its isolated Downloads folder',path.resolve(result.path).startsWith(path.resolve(path.join(out,'home','Downloads'))+path.sep));const exported=JSON.parse(await readFile(result.path,'utf8'));const source=JSON.parse(await readFile(fixture,'utf8'));check('Export retains exact original source and the edited caption',exported.source.text===source.source.text&&exported.pages[0].text.endsWith(' Desktop revision.'));await page.screenshot({path:path.join(out,'desktop-editor.png'),fullPage:true});check('No renderer errors',report.pageErrors.length===0);report.outcome='passed';
}catch(error){report.outcome='failed';report.failure=error.stack;process.exitCode=1;}finally{await app?.close().catch(()=>{});await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({outcome:report.outcome,checks:report.checks.length,failure:report.failure}));}
