import {loadShowcase} from './data/showcase';
import {sceneCharacters} from '../shared/illustration.mjs';
import React,{useEffect,useRef,useState,useCallback} from 'react';
import {BookOpen,PlusSquare,Settings as SettingsIcon,Upload,ChevronLeft,ChevronRight,ZoomIn,Undo2,Redo2,Plus,Trash2,X,Volume2,Square,Download,FileJson,Image,Check,Loader2} from 'lucide-react';
import {blankBook,uid} from '../shared/book.mjs';import {saveBook,readBook,listBooks,removeBook,storageStatus} from './lib/storage';import {defaults,adaptStory,illustrate} from './lib/generation';import {fileToImage} from './lib/imports';import {exportProject,exportPDF,exportPage} from './lib/export';import {Modal,Field} from './components/Modal';import NewBook from './components/NewBook';import Settings from './components/Settings';import BookCanvas from './components/BookCanvas';import Inspector from './components/Inspector';
export default function App(){
  const [book,setBook]=useState(blankBook),[index,setIndex]=useState(0),[tab,setTab]=useState('Story'),[modal,setModal]=useState(''),[settings,setSettings]=useState(defaults),[config,setConfig]=useState({local:false,configured:false}),[books,setBooks]=useState([]),[toast,setToast]=useState(null),[saveState,setSaveState]=useState('Loading'),[busy,setBusy]=useState(''),[reading,setReading]=useState(false),[speaking,setSpeaking]=useState(false),[zoom,setZoom]=useState('fit'),[installPrompt,setInstallPrompt]=useState(null),[ready,setReady]=useState(false),[revision,setRevision]=useState(0),[pending,setPending]=useState(null);
  const abortRef=useRef(),bookRef=useRef(book),history=useRef({past:[],future:[]}),toastTimer=useRef();bookRef.current=book;
  const notify=useCallback((message,type='info')=>{setToast({message,type});clearTimeout(toastTimer.current);if(type!=='error')toastTimer.current=setTimeout(()=>setToast(null),9000);},[]);
  useEffect(()=>{let alive=true;(async()=>{try{const id=sessionStorage.getItem('picturebook:last')||localStorage.getItem('picturebook:last');if(id){const saved=await readBook(id);if(saved?.pages?.length&&alive){setBook(saved);return;}}if(alive)setBook(await loadShowcase());}catch{notify('Browser storage is unavailable. Export a project to keep your work.','error');}finally{if(alive)setReady(true);}})();fetch('/api/config').then(r=>r.json()).then(setConfig).catch(()=>{});const install=e=>{e.preventDefault();setInstallPrompt(e);};window.addEventListener('beforeinstallprompt',install);return()=>{alive=false;window.removeEventListener('beforeinstallprompt',install);window.speechSynthesis?.cancel();};},[]);
  useEffect(()=>{if(!ready)return;try{sessionStorage.setItem('picturebook:last',book.id);}catch{}setSaveState('Saving');const timer=setTimeout(()=>saveBook(book).then(()=>setSaveState('Saved on this device')).catch(()=>{setSaveState('Not saved');notify('Your browser could not save this book. Export a project now to keep it.','error');}),550);return()=>clearTimeout(timer);},[book,ready]);
  useEffect(()=>{window.speechSynthesis?.cancel();setSpeaking(false);},[index,reading]);
  useEffect(()=>{const onKey=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(modal)return;if(e.key==='ArrowRight')setIndex(i=>Math.min(i+1,book.pages.length-1));if(e.key==='ArrowLeft')setIndex(i=>Math.max(0,i-1));if(e.key==='Escape')setReading(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[book.pages.length,modal]);
  useEffect(()=>{if(index>=book.pages.length)setIndex(Math.max(0,book.pages.length-1));},[book.pages.length,index]);
  function mutate(fn){setBook(old=>{history.current.past.push(old);if(history.current.past.length>40)history.current.past.shift();history.current.future=[];return fn(old);});setRevision(v=>v+1);}
  function updatePage(patch){mutate(b=>({...b,pages:b.pages.map((p,i)=>i===index?{...p,...patch}:p)}));}
  function updateBook(patch){mutate(b=>({...b,...patch}));}
  function undo(){const h=history.current;if(!h.past.length)return;h.future.push(book);setBook(h.past.pop());setRevision(v=>v+1);}
  function redo(){const h=history.current;if(!h.future.length)return;h.past.push(book);setBook(h.future.pop());setRevision(v=>v+1);}
  async function openBook(value){if(busy)return;await saveBook(bookRef.current).catch(()=>{});history.current={past:[],future:[]};setBook(value);setIndex(0);setTab('Story');setModal('');storageStatus().catch(()=>{});}
  async function library(){setBooks(await listBooks());setModal('library');}
  function connected(){if(settings.provider==='local'&&config.local)return true;if(settings.key||config.configured)return true;setModal('settings');notify('Connect a generation service, then return to your story.');return false;}
  async function work(label,fn){if(busy)return;const controller=new AbortController();abortRef.current=controller;setBusy(label);try{await fn(controller.signal);}catch(e){if(e.name==='AbortError')notify('Stopped. Completed pages have been kept.');else notify(e.message,'error');}finally{setBusy('');abortRef.current=null;}}
  async function adapt(source,options){setPending({source,options});if(!connected())return;setModal('');await work('Reading your story…',async signal=>{const created=await adaptStory(source,options,settings,{signal,onProgress:setBusy});await saveBook(created);setPending(null);history.current={past:[],future:[]};setBook(created);setIndex(0);setTab('Story');notify('Your adaptation is ready. Review the story, then illustrate it.');});}
  async function createIllustration(){if(!connected())return;const current=bookRef.current;const page=current.pages[index];await work('Illustrating this spread…',async signal=>{const image=await illustrate(current,page,settings,signal);mutate(b=>({...b,pages:b.pages.map(p=>p.id===page.id?{...p,image,imageCast:sceneCharacters(current,p).map(c=>c.name),alt:p.scene}:p)}));notify('New illustration saved. Undo brings back the previous version.');});}
  async function createReference(){if(!connected())return;await work('Creating the character reference…',async signal=>{const image=await illustrate(bookRef.current,null,settings,signal,{referenceOnly:true});updateBook({referenceImage:image,referenceCast:bookRef.current.characters.slice(0,4).map(c=>c.name)});});}
  async function illustrateAll(){if(!connected())return;await work('Preparing the book’s visual reference…',async signal=>{let current=bookRef.current;const missing=current.pages.filter(p=>!p.image);for(let n=0;n<missing.length;n++){signal.throwIfAborted();setBusy(`Illustrating spread ${n+1} of ${missing.length}…`);const image=await illustrate(current,missing[n],settings,signal);current={...current,pages:current.pages.map(p=>p.id===missing[n].id?{...p,image,imageCast:sceneCharacters(current,p).map(c=>c.name),alt:p.scene}:p)};setBook(current);await saveBook(current);}notify('Your illustrations are ready.');});}
  async function upload(file,reference){if(!file)return;try{const data=await fileToImage(file);reference?updateBook({referenceImage:data,referenceCast:bookRef.current.characters.map(c=>c.name)}):updatePage({image:data});}catch(e){notify(e.message,'error');}}
  function addSpread(){mutate(b=>({...b,pages:[...b.pages,{id:uid(),title:'A new chapter',text:'',scene:'',sourceNote:'',image:'',alt:''}]}));setIndex(book.pages.length);}
  function deleteSpread(){if(book.pages.length<=1)return;mutate(b=>({...b,pages:b.pages.filter((_,i)=>i!==index)}));setIndex(i=>Math.min(i,book.pages.length-2));setModal('');}
  function narrate(){if(speaking){speechSynthesis.cancel();setSpeaking(false);return;}if(!('speechSynthesis'in window)){notify('Read aloud is not supported in this browser.');return;}const utterance=new SpeechSynthesisUtterance(book.pages[index].title+'. '+book.pages[index].text);utterance.rate=.86;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>setSpeaking(false);speechSynthesis.speak(utterance);setSpeaking(true);}
  async function install(){if(installPrompt){await installPrompt.prompt();setInstallPrompt(null);}else{setModal('install');}}
  const webRef=useRef();webRef.current={book,index,busy,setIndex,updatePage};
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
    register({name:'read_picture_book',title:'Read the open book',description:'Read the open book’s title, characters, spread text, scene directions, source notes, and illustration completion. Does not return API keys, original document text, or image bytes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const s=webRef.current;return {title:s.book.title,author:s.book.author,currentSpread:s.index+1,progress:s.busy,characters:s.book.characters,spreads:s.book.pages.map((p,i)=>({spread:i+1,title:p.title,text:p.text,scene:p.scene,sourceNote:p.sourceNote,illustrated:!!p.image}))};}});
    register({name:'show_picture_book_spread',title:'Show a spread',description:'Navigate the visible editor to a numbered spread in the open book.',inputSchema:{type:'object',properties:{spread:{type:'integer',minimum:1}},required:['spread'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const s=webRef.current;if(!Number.isInteger(input.spread)||input.spread<1||input.spread>s.book.pages.length)throw new Error('Choose an existing spread number.');s.setIndex(input.spread-1);return {spread:input.spread,title:s.book.pages[input.spread-1].title};}});
    return()=>lifecycle.abort();
  },[]);
  const page=book.pages[Math.min(index,book.pages.length-1)];if(!page)return <main>Loading your book…</main>;
  return <div className={'app '+(reading?'reading':'')}>
    <header className="topbar"><button className="brand" onClick={()=>{setReading(false);}} aria-label="Picture Book editor"><BookOpen size={38} strokeWidth={1.6}/><span>Picture Book</span></button><div className="header-divider"/><nav aria-label="Workspace"><button aria-label="My library" onClick={library} disabled={!!busy}><BookOpen size={21}/><span>My library</span></button><button aria-label="New book" onClick={()=>setModal('new')} disabled={!!busy}><PlusSquare size={21}/><span>New book</span></button><button aria-label="Settings" onClick={()=>setModal('settings')} disabled={!!busy}><SettingsIcon size={21}/><span>Settings</span></button></nav><div className="header-actions">{reading?<><button aria-label={speaking?'Stop reading':'Read aloud'} onClick={narrate}><Volume2 size={20}/><span>{speaking?'Stop reading':'Read aloud'}</span></button><button aria-label="Edit" onClick={()=>setReading(false)}><X size={20}/><span>Edit</span></button></>:<button aria-label="Read" onClick={()=>setReading(true)}><BookOpen size={22}/><span>Read</span></button>}<button className="primary export-button" aria-label="Export" onClick={()=>setModal('export')} disabled={!!busy}><Upload size={21}/><span>Export</span></button></div></header>
    <div className="document-bar"><button className="document-title" disabled={!!busy} onClick={()=>setModal('details')} title="Edit book details">{book.title}</button><span className="document-count">{book.pages.length*2} pages</span><span className="saved"><Check size={13}/>{saveState}</span>{!reading&&<div className="history"><button className="icon-button" aria-label="Undo" disabled={!history.current.past.length||!!busy} onClick={undo}><Undo2 size={17}/></button><button className="icon-button" aria-label="Redo" disabled={!history.current.future.length||!!busy} onClick={redo}><Redo2 size={17}/></button></div>}</div>
    <div className="workspace">{!reading&&<aside className="page-rail" aria-label="Book pages">{book.pages.flatMap((p,i)=>[<button key={p.id+'a'} className={'thumbnail '+(index===i?'selected':'')} aria-label={`Spread ${i+1}: ${p.title}`} aria-current={index===i?'page':undefined} onClick={()=>setIndex(i)}><span className="thumb-art">{p.image?<img src={p.image} alt=""/>:<Image size={24}/>}</span><span>{i*2+1}</span></button>,<button key={p.id+'t'} className={'thumbnail text-thumb '+(index===i?'paired':'')} aria-label={`Story page ${i*2+2}`} onClick={()=>{setIndex(i);setTab('Story');}}><span className="thumb-copy">{p.title}<i>{p.text.slice(0,54)}</i></span><span>{i*2+2}</span></button>])}<button className="add-page" onClick={addSpread} disabled={book.pages.length>=24||!!busy}><Plus size={20}/><span>Add spread</span></button></aside>}
    <main className={'canvas-area '+(zoom==='100'?'actual-size':'')}><div className="canvas-scroll"><BookCanvas book={book} index={index} reading={reading} onArt={()=>{setTab('Art');setReading(false);}}/></div><div className="canvas-footer"><div className="page-navigation"><button className="square-button" aria-label="Previous spread" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronLeft size={23}/></button><span>{index*2+1} – {index*2+2} of {book.pages.length*2}</span><button className="square-button" aria-label="Next spread" disabled={index===book.pages.length-1} onClick={()=>setIndex(i=>i+1)}><ChevronRight size={23}/></button></div><div className="canvas-tools">{!reading&&<button className="icon-button" title="Remove this spread" aria-label="Remove this spread" disabled={book.pages.length<=1||!!busy} onClick={()=>setModal('deleteSpread')}><Trash2 size={17}/></button>}<label className="zoom-control"><ZoomIn size={18}/><select aria-label="Canvas zoom" value={zoom} onChange={e=>setZoom(e.target.value)}><option value="fit">Fit</option><option value="100">100%</option></select></label></div></div></main>
    {!reading&&<Inspector book={book} page={page} tab={tab} setTab={setTab} updatePage={updatePage} updateBook={updateBook} onIllustrate={createIllustration} onIllustrateAll={illustrateAll} onReference={createReference} onUpload={upload} busy={!!busy}/>}</div>
    {modal==='new'&&<NewBook initial={pending} onClose={()=>setModal('')} onCreate={openBook} onImport={openBook} onAdapt={adapt} notify={notify}/>}
    {modal==='settings'&&<Settings settings={settings} config={config} onClose={()=>setModal('')} onSave={v=>{setSettings(v);setModal(pending?'new':'');notify('Settings saved for this session.');}} onInstall={install} installPrompt={installPrompt}/>}
    {modal==='details'&&<Modal title="Book details" onClose={()=>setModal('')}><Field label="Title"><input value={book.title} maxLength={200} onChange={e=>updateBook({title:e.target.value})}/></Field><Field label="Author"><input value={book.author} maxLength={100} onChange={e=>updateBook({author:e.target.value})} placeholder="Your name"/></Field><p className="note">{book.source.name?`Source: ${book.source.name}`:'An original book, made by you.'}</p><button className="primary" onClick={()=>setModal('')}>Done</button></Modal>}
    {modal==='library'&&<Modal title="Your library" wide onClose={()=>setModal('')}><p className="intro">Saved on this device. Export projects to move them between computers.</p><div className="library-grid">{books.map(b=><article key={b.id}><button className="library-book" onClick={()=>openBook(b)}>{b.pages[0]?.image?<img src={b.pages[0].image} alt=""/>:<BookOpen size={50}/>}<strong>{b.title}</strong><span>{b.pages.length*2} pages</span></button><button className="text-button" onClick={async()=>{await removeBook(b.id);setBooks(await listBooks());notify('Removed from this device. Exported copies are unaffected.');}}>Remove saved copy</button></article>)}</div><div className="modal-actions"><button className="secondary" onClick={()=>work('Opening Alice…',async()=>{const example=await loadShowcase();await saveBook(bookRef.current);history.current={past:[],future:[]};setBook(example);setIndex(0);setModal('');})}>Open Alice showcase</button><button className="primary" onClick={()=>setModal('new')}>New book</button></div></Modal>}
    {modal==='export'&&<Modal title="Keep your book" onClose={()=>setModal('')}><p className="intro">{book.title} · {book.pages.length*2} pages</p><div className="export-options"><button onClick={()=>{setModal('');work('Preparing PDF…',signal=>exportPDF(book,setBusy,signal));}}><Download/><span><strong>Download PDF</strong><small>Complete book, ready to read or print</small></span></button><button onClick={()=>{setModal('');work('Packing your project…',()=>exportProject(book));}}><FileJson/><span><strong>Save editable project</strong><small>Includes the story, characters, and every illustration</small></span></button><button onClick={()=>{setModal('');work('Saving illustration…',()=>exportPage(book,index));}}><Image/><span><strong>Save this illustration</strong><small>PNG image of the current art page</small></span></button></div><p className="note">Your original source is included in editable projects. Share only what you intend to share.</p></Modal>}
    {modal==='deleteSpread'&&<Modal title="Remove this spread?" onClose={()=>setModal('')}><p>Remove “{page.title}” and its illustration from this book. You can undo this change.</p><div className="modal-actions"><button className="secondary" onClick={()=>setModal('')}>Keep it</button><button className="primary" onClick={deleteSpread}>Remove spread</button></div></Modal>}
    {modal==='install'&&<Modal title="Install Picture Book" onClose={()=>setModal('')}><p>In Chrome or Edge, open the browser menu and choose <strong>Install app</strong> or <strong>Install Picture Book</strong>.</p><p>On iPhone or iPad, open the site in Safari, tap Share, then Add to Home Screen.</p><p className="note">A desktop download is also available with the open-source release. The web app caches its editor. Your books stay in this browser’s storage.</p></Modal>}
    {busy&&<div className="busy-banner" role="status"><Loader2 size={19} className="spin"/><span>{busy}</span><button onClick={()=>abortRef.current?.abort()}>Stop</button></div>}
    {toast&&<div className={'toast '+toast.type} role={toast.type==='error'?'alert':'status'}><span>{toast.message}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setToast(null)}><X size={18}/></button></div>}
  </div>;
}
